# Generated by Django 5.2.1 on 2025-05-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('FOODBANK', 'Foodbank'), ('RECIPIENT', 'Recipient'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
